Repository moevm/mse1h2025-prctr, pull requests merged in 2025-03, with the labels that each got.

#19 popup_view_9
  client/index.html
  client/manifest.json
  client/style.css
Labels: In Review

#21 selinux_docker_support_20
  server/Dockerfile
  server/docker-compose.yml
Labels: In Review

#18 expanding_fields_11
  client/index.html
  client/index.js
  client/style.css
Labels: In Review

#17 Saving_7
  client/background.js
  client/common.js
  client/index.html
  client/index.js
  client/manifest.json
Labels: In Review

#25 background_activity_8
  client/background.js
  client/common.js
  client/icon.png
  client/index.html
  client/index.js
  client/manifest.json
  client/media.css
  client/media.html
  client/media.js
Labels: In Review

#30 database_template_13
  server/app.py
Labels: In Review

#32 data_exchange_server_24
  server/app.py
Labels: In Review

#38 update_library_versions_37
  server/requirements.txt
Labels: In Review

#31 initialization_with_client_10
  server/app.py
Labels: In Review

#39 permanent_microphone_access_35
  client/media.js
Labels: bug, need info

#42 initialization_with_server_27
  client/index.js
  server/app.py
Labels: In Review

#44 data_exchange_client_23
  .gitignore
  client/media.js
  server/app.py
Labels: In Review

#41 Saving_fields_36
  client/index.js
Labels: bug, In Review, fixed

#47 date_format_46
  server/app.py
Labels: In Review

#50 support_rewind_28
  client/media.js
Labels: In Review, need info

#49 first_server_usage_scenario_12
  server/app.py
Labels: In Review

#45 docker_14
  server/Dockerfile
  server/docker-compose.yml
Labels: In Review

#40 Add_webcam_to_proctoring_29
  client/index.js
  client/media.css
  client/media.html
  client/media.js
  server/app.py
Labels: In Review

#60 server_gui_52
  server/app.py
  server/static/filter.css
  server/static/filter.js
  server/static/filter_result.css
  server/templates/filter.html
  server/templates/filter_result.html
Labels: In Review

#61 reliability_recording_stop_59
  client/media.js
Labels: bug, In Review

#55 metadata_51
  client/media.html
  client/media.js
  server/app.py
Labels: In Review

#56 visual_popup_improvements_53
  client/index.html
  client/style.css
Labels: In Review

#58 logging_43
  client/background.js
  client/index.js
  client/logger.js
  client/manifest.json
  client/media.js
  server/app.py
Labels: In Review

#73 gui_not_all_data_72
  server/app.py
  server/static/filter.js
  server/static/filter_result.css
Labels: bug, In Review
