Repository moevm/mse1h2025-prctr, pull requests merged in 2025-04, with the labels that each got.

#76 room_link_field_75
  client/index.html
  client/index.js
  server/app.py
  server/static/filter.js
Labels: In Review

#77 button_functionality_69
  client/background.js
  client/common.js
  client/index.html
  client/index.js
  client/media.js
  client/style.css
Labels: In Review

#74 early_initialization_with_server_54
  client/background.js
  client/index.js
  client/manifest.json
  client/media.css
  client/media.js
Labels: bug, In Review

#81 multiple_pages_perm_settings_80
  client/media.js
Labels: bug, In Review

#86 release_attacher_85
  .github/workflows/release_attacher.yml
Labels: In Review

#89 control_close_tab_browser_71
  client/media.html
  client/media.js
Labels: In Review

#92 server_off_client_ability_78
  client/index.js
  client/media.js
Labels: In Review

#95 update_input_checking_87
  client/index.js
  client/style.css
Labels: In Review

#99 extension_icon_97
  client/assets/icon.png
  client/assets/icon_record.png
  client/icon.png
  client/manifest.json
Labels: In Review

#96 screen_permissions_93
  client/media.js
Labels: In Review

#105 camera_permissions_94
  client/index.js
  client/media.css
  client/media.html
  client/media.js
  client/style.css
  server/app.py
Labels: In Review, waiting

#106 fix_log_clearing_111
  client/background.js
Labels: bug, In Review, waiting

#83 dynamic_popup_stats_68
  client/background.js
  client/index.html
  client/index.js
  client/media.js
  client/style.css
Labels: In Review

#114 add_size_popup_optimization_112
  client/index.html
  client/media.css
  client/style.css
Labels: In Review

#108 save_logs_server_down_109
  client/background.js
  client/media.js
Labels: bug, fixed

#117 gotoMediaTab_error_port_113
  client/scripts/background.js
  client/scripts/common.js
  client/scripts/index.js
  client/scripts/media.js
  client/styles/media.css
Labels: bug, fixed, need info

#126 update_documentation_124
  README.md
  client/README.md
  client/assets/docs/loadedExtension.png
  client/assets/docs/openPinnedPopup.png
  client/assets/docs/openPopup.png
  client/assets/docs/popupLocation.png
  client/assets/help/readme.html
  client/manifest.json
Labels: In Review

#130 Improve_log_stability_115
  README.md
  client/README.md
  client/assets/help/readme.html
  client/manifest.json
  client/scripts/background.js
  client/scripts/common.js
  client/scripts/logger.js
  client/scripts/media.js
Labels: bug

#132 fix_show_cue_on_active_tab_116
  client/scripts/background.js
  client/scripts/common.js
  client/scripts/content.js
  client/scripts/index.js
  client/scripts/media.js
  client/styles/index.css
  client/styles/media.css
Labels: bug, fixed
