Repository moevm/mse1h2025-prctr, pull requests merged in 2025-05, with the labels that each got.

#139 add_tests_for_server_138
  .github/workflows/tester.yml
  tests/integration_test.py
  tests/requirements.txt
  tests/run_tests.sh
Labels: In Progress, In Review

#133 Improve upload scenario #127
  client/scripts/background.js
  client/scripts/common.js
  client/scripts/index.js
  client/scripts/logger.js
  client/scripts/media.js
  client/styles/index.css
  server/app.py
Labels: In Review

#140 Fix screen status loss during proctoring #135
  client/scripts/background.js
Labels: bug, fixed

#151 Fix multi init in one session #145
  client/scripts/media.js
Labels: In Review

#183 Add dynamic microphone icon #174
  client/assets/icons/mic.svg
  client/pages/media.html
  client/scripts/media.js
  client/styles/media.css
Labels: In Review

#181 Fix preview full screen #168
  client/pages/media.html
  client/scripts/media.js
  server/app.py
Labels: bug, In Review, fixed
